#!/usr/bin/env bash
# Deploys the Payper contracts to testnet and writes their ids to .env.local.
set -euo pipefail

NETWORK="${NETWORK:-testnet}"
ADMIN="${ADMIN:-payper-admin}"
USDC_ISSUER="${USDC_ISSUER:-GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5}"
OUT="${OUT:-.env.local}"
WASM=target/wasm32v1-none/release

say() { printf '\n\033[1m%s\033[0m\n' "$*"; }

say "1/5  Kontratlar derleniyor"
cargo build --release --target wasm32v1-none --quiet
ls -la $WASM/*.wasm | awk '{printf "     %-46s %7d bayt\n", $9, $5}'

ADMIN_ADDR=$(stellar keys address "$ADMIN")
TOKEN=$(stellar contract id asset --asset "USDC:$USDC_ISSUER" --network "$NETWORK")
say "2/5  USDC varlık kontratı"
echo "     $TOKEN"

say "3/5  TRY/USD beslemesi deploy ediliyor"
FX=$(stellar contract deploy --wasm "$WASM/payper_fx_oracle.wasm" \
      --source "$ADMIN" --network "$NETWORK" 2>/dev/null | tail -1)
echo "     $FX"
stellar contract invoke --id "$FX" --source "$ADMIN" --network "$NETWORK" --send=yes -- \
  init --admin "$ADMIN_ADDR" --publisher "$ADMIN_ADDR" \
  --decimals 14 --resolution 300 --capacity 400 >/dev/null
echo "     init ✓  (decimals 14 · resolution 300 · kapasite 400)"

say "4/5  Hazine ve fatura kontratı"
TREASURY=$(stellar contract deploy --wasm "$WASM/payper_treasury_local.wasm" \
      --source "$ADMIN" --network "$NETWORK" 2>/dev/null | tail -1)
echo "     hazine   $TREASURY"
stellar contract invoke --id "$TREASURY" --source "$ADMIN" --network "$NETWORK" --send=yes -- \
  init --admin "$ADMIN_ADDR" --token "$TOKEN" --apy_bps 800 >/dev/null

INVOICE=$(stellar contract deploy --wasm "$WASM/payper_invoice.wasm" \
      --source "$ADMIN" --network "$NETWORK" 2>/dev/null | tail -1)
echo "     fatura   $INVOICE"

# These mirror the values the unit tests pin, so deployed behaviour matches
# tested behaviour. whitelist_threshold is 15 USDC: above that a funder must be
# licensed, which is what the demo's larger ticket crosses.
stellar contract invoke --id "$INVOICE" --source "$ADMIN" --network "$NETWORK" --send=yes -- \
  init --config "{
    \"admin\": \"$ADMIN_ADDR\",
    \"treasury\": \"$TREASURY\",
    \"token\": \"$TOKEN\",
    \"oracle\": \"$FX\",
    \"oracle_asset\": \"TRY\",
    \"oracle_samples\": 30,
    \"credit_premium_bps\": 120,
    \"platform_fee_bps\": 50,
    \"fallback_apy_bps\": 800,
    \"fallback_fx_annual_bps\": 2500,
    \"fx_floor_bps\": 50,
    \"fx_cap_bps\": 2500,
    \"whitelist_threshold\": \"150000000\",
    \"grace_period\": 259200,
    \"quote_ttl\": 86400
  }" >/dev/null
echo "     init ✓"

# Only the invoice contract may draw pooled capital out.
stellar contract invoke --id "$TREASURY" --source "$ADMIN" --network "$NETWORK" --send=yes -- \
  set_controller --controller "$INVOICE" >/dev/null
echo "     hazine controller → fatura kontratı ✓"

say "5/5  Adresler $OUT dosyasına yazılıyor"
cat > "$OUT" <<ENV
# Generated by scripts/deploy.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)
PUBLIC_STELLAR_NETWORK=$NETWORK
PUBLIC_NETWORK_PASSPHRASE="Test SDF Network ; September 2015"
PUBLIC_RPC_URL=https://soroban-testnet.stellar.org
PUBLIC_HORIZON_URL=https://horizon-testnet.stellar.org

PUBLIC_INVOICE_CONTRACT_ID=$INVOICE
PUBLIC_TREASURY_CONTRACT_ID=$TREASURY
PUBLIC_FX_ORACLE_CONTRACT_ID=$FX
PUBLIC_USDC_CONTRACT_ID=$TOKEN
PUBLIC_USDC_ISSUER=$USDC_ISSUER

PUBLIC_ANCHOR_HOME_DOMAIN=tr-mock-anchor.fly.dev
PUBLIC_ANCHOR_ASSET_CODE=USDC
PUBLIC_FIAT_ASSET_CODE=TRY
PUBLIC_TREASURY_MODE=local
ENV
cat "$OUT" | sed 's/^/     /'
